;--------------------------------------------------------------------------------
; winPenPack Project § X-Software collection
; Copyright © 2005-2014 Danilo Leggieri and winPenPack Development Team
; X-Launcher 1.5.4 Copyright © Gabriele Tittonel and winPenPack Development Team
;
; Web: http://www.winpenpack.com/
; E-mail: winpenpack@gmail.com
;
; Released under the terms and conditions of the winPenPack License Agreement 
; (see license.txt or http://www.winpenpack.com/main/page.php?5)
;--------------------------------------------------------------------------------


;=================================================
; ** X-Launcher's configuration file **
;=================================================

[Setup]
AppName=MyApp
; AppVer=
; UserName=User
; Profile=Default
; Lang=%LANG%

;-------------------------------------------------
; [FileSystem]
; Root=@ScriptDir@
; Temp=@TempDir@\$ScriptName$
; Cache=@TempDir@\$ScriptName$\Cache
; Home=.\$UserName$
; Bin=.\Bin
; Lib=.\Lib
; Doc=.\Documents
; Backup=.\Backups
; Download=.\Downloads

;-------------------------------------------------
; ** Path syntax **
;-------------------------------------------------
; ALL RELATIVE PATHS ARE RELATIVE TO "Root" (and "Root" is relative to "@ScriptDir@")

; \Path --> path relative to root drive
; .\Path --> path relative to root
; ..\Path --> path relative to one level up
; ..\..\Path --> up two leves, and go on
; X:\Path -> absolute path

;-------------------------------------------------
[FileToRun]
PathToExe=$Bin$\$AppName$\$AppName$.exe
; *** for Java software use: 
; PathToExe=$Java$\bin\javaw.exe
Parameters=
WorkingDir=
WinGetProcess=

;-------------------------------------------------
[Options]
DeleteTemp=true
MultipleIstances=true
FixAppData=false
RunWait=true
ShowSplash=true
ShowTrayTip=true
WriteLog=false
HideShellWindow=true
; *** to execute [FirstRunOperations] section (only at the very first run)
FirstRun=false
; *** to activate Java software
Java=false
; *** to activate verbose log
Debug=true

;-------------------------------------------------
[SplashScreen]
Image=
Title=
TimeOut=1500
Width=
Height=

;-------------------------------------------------
[TrayTip]
Title=
Timeout=5000

;-------------------------------------------------
[Environment]
; HOME=$Home$\$AppName$
; PATH=%PATH%;@ScriptDir@
; LANG=$Lang$
; USERPROFILE=%HOME%
; MY_VAR=MY_VALUE|(Options) = Or ~%20\\/"

;-------------------------------------------------
; ** String transformation **
;-------------------------------------------------
; = --> returns the original string (not interpreted as path)
; ~ --> returns the 8.3 short path+name of the string passed
; %20 --> replaces blanck spaces with '%20'
; \\ --> replaces '\' with '\\'
; / --> replaces '\' with '/'
; " --> returns the string enclosed between apexes: "String"
;-------------------------------------------------

[Functions]
; DirCopy=(Source)Path|(Destination)Path|(Option) o
; DirCreate=Path1\SubPath1;SubPath2|Path2|Path3\SubPath3
; DirMove=(Source)Path|(Destination)NewPath|(Option) o
; DirRemove=Path|(Option) e
; FileCopy=(Source)Path\file1;file2;file3|(Destination)Path\|(Option) o
; FileCopy=(Source)Path\file|(Destination)Path\(Or)File|(Option) o
; FileDelete=Path1\file1;file2|Path2\file3
; FileCreate=Path1\file1;file2|Path2\file3
; FileMove=(Source)Path\File|(Destination) NewPath\NewFile|(Option) o
; AddFonts=Path\File.Ext ("*" wildcard allowed)

; o --> overwrite mode
; e --> remove if empty

;-------------------------------------------------
[FirstRunOperations]
; DirCopy=(Source)Path|(Destination)Path|(Option) o
; DirCreate=Path1\SubPath1;SubPath2|Path2|Path3\SubPath3
; DirMove=(Source)Path|(Destination)NewPath|(Option) o
; DirRemove=Path|(Option) e
; FileCopy=(Source)Path\file1;file2;file3|(Destination)Path\|(Option) o
; FileCopy=(Source)Path\file|(Destination)Path\(Or)File|(Option) o
; FileDelete=Path1\file1;file2|Path2\file3
; FileCreate=Path1\file1;file2|Path2\file3
; FileMove=(Source)Path\File|(Destination) NewPath\NewFile|(Option) o
; RunFile=Path\File|Parameters

; o --> overwrite mode
; e --> remove if empty

;-------------------------------------------------
; [StringReplace=Path\File]
; Begin|End|(o)=Replace|(Options) = Or ~%20\\/" 

;-------------------------------------------------
; [StringRegExpReplace=Path\File]
; Spacer|Counter|(Option)=PatternSpacerReplace

;-------------------------------------------------
; [WriteToFile=Path\File]
; Line1=This is the first line
; Line2=Some text
; LineX=
; EOF=This is the last line

;-------------------------------------------------
; [WriteToIni=Path\File]
; Section|Key=Value|(Options) = Or ~%20\\/"

;-------------------------------------------------
; [WriteToPref=Path\File]
; Format=begin[PREF]mid[VALUE]end
; MyPref=MyValue|(Options) = Or ~%20\\/"

;-------------------------------------------------
; [WriteToReg=Path\File]
; MainKey=MAIN_KEY
; Value=Content|(Options) = Or ~%20\\/"
; SubKey|Value=Content|(Options) = Or ~%20\\/"

;-------------------------------------------------
; [RunBefore]
; Regedit=Path1\File1.reg;File2.reg|Path2\File3.reg
; RunFile=Path\File|Parameters
; FixDriveLetter=Path\File|(Options) skip*

; skip=ABC... --> do not replace skip letter(s)
; * --> not case sensitive

;-------------------------------------------------
; [RunAfter]
; RunFile=Path\File|Parameters
; DirCopy=(Source)Path|(Destination)Path|(Option) o
; DirMove=(Source)Path|(Destination)NewPath|(Option) o
; DirRemove=Path
; FileCopy=(Source)Path\file1;file2;file3|(Destination)Path\|(Option) o
; FileCopy=(Source)Path\file|(Destination)Path\(Or)File|(Option) o
; FileDelete=Path1\file1;file2|Path2\file3
; FileMove=(Source)Path\File|(Destination) NewPath\NewFile|(Option) o

; o --> overwrite mode
;=================================================
